#!/bin/bash
echo "=== Email-Tab Debug ==="
echo ""
echo "1. Email-Worker Status:"
ps aux | grep email_worker | grep -v grep || echo "   ❌ NICHT LÄUFT!"
echo ""
echo "2. Datenbank-Status:"
sqlite3 data/email_cache.db "SELECT status, COUNT(*) FROM emails GROUP BY status;" 2>/dev/null || echo "   ❌ DB nicht gefunden"
echo ""
echo "3. Pending Actions:"
sqlite3 data/email_cache.db "SELECT action_type, COUNT(*) FROM actions WHERE status='pending' GROUP BY action_type;" 2>/dev/null || echo "   Keine pending actions"
echo ""
echo "4. Streamlit Prozesse:"
ps aux | grep streamlit | grep -v grep | wc -l | xargs echo "   Anzahl:"
echo ""
echo "5. App Log (letzte 10 Zeilen):"
tail -10 streamlit.log 2>/dev/null || echo "   Kein Log gefunden"
